# Generated by Django 3.1.3 on 2020-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201206_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
