# Generated by Django 3.1.3 on 2020-12-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201206_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='PostCommentModel',
        ),
    ]
