# Generated by Django 3.1.3 on 2020-12-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201206_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCommentModel',
        ),
    ]
