# Generated by Django 3.1.3 on 2020-12-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_commentpostmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPostModel',
        ),
    ]
