# Generated by Django 3.1.3 on 2020-12-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_commentpostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpostmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='commentpostmodel',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_in', to='posts.post'),
            preserve_default=False,
        ),
    ]
