# Generated by Django 3.1.3 on 2020-12-08 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_commentpostmodel_user_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpostmodel',
            name='user_comm',
            field=models.ManyToManyField(related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
