# Generated by Django 3.1.3 on 2020-12-08 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_auto_20201208_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpostmodel',
            name='user_comm',
        ),
        migrations.AddField(
            model_name='commentpostmodel',
            name='user_comm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='auth.user'),
            preserve_default=False,
        ),
    ]
