# Generated by Django 3.1.3 on 2020-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201208_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpostmodel',
            name='comments',
            field=models.TextField(max_length=100),
        ),
    ]
