# Generated by Django 3.1.3 on 2020-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201211_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_img'),
        ),
    ]
